title: Dentsply Sirona Product Classifier
description: Classify DS Products
about:


  This is a product Classifier of Dentsply Sirona using Deep Learning built on top of Pytorch.


  The project was build by [Nidhin Pattaniyil](https://npatta01.github.io)
  and [Reshama Shaikh](https://reshamas.github.io).


  More info and the source code can he found below.
  - [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)    
  - [Web app](https://food-img-classifier.herokuapp.com)
  - [Video](https://www.youtube.com/watch?v=7d2qFLeYvRc)


  To try out this mobile app
    - [Expo](https://expo.io/@npatta01/food-app)
    - [Android](https://play.google.com/store/apps/details?id=com.rsnp.foodclassifier)
    - [iOS](https://itunes.apple.com/us/app/food-classifier/id1445356461?ls=1&mt=8)



code: https://github.com/npatta01/web-deep-learning-classifier

sampleImages:
  - name: inLab
    url: https://drive.google.com/open?id=1MBOLDqDkZD2Kx4qdZeEt5CLztLk-CS9I
  - name: inEos X5
    url: https://drive.google.com/open?id=1LpIRcJ5IZxJWCm-vyulDqXzHIlgArz9B
  - name: Speed Fire
    url: https://drive.google.com/open?id=1w2ZeTET37oFAzJOS9qq6hD-1t2vbwiEO
  - name: Prime Scan
    url: https://drive.google.com/open?id=1W8llEYO0zx0WgxE5VCwHW4SCfIAkIYZw
  - name: table (not in training)
    url: https://image.shutterstock.com/image-photo/brown-light-wooden-round-dining-260nw-588358070.jpg 
