title: Pet Images Classifier
description: Classify pet images - fastai pretrained model
about:


  This is a Pet Images Classifier using Deep Learning built on top of Pytorch.


  The project was build by [Nidhin Pattaniyil](https://npatta01.github.io)
  and [Reshama Shaikh](https://reshamas.github.io).


  More info and the source code can he found below.
  - [Blog](https://reshamas.github.io/deploying-deep-learning-models-on-web-and-mobile/)    
  - [Web app](https://food-img-classifier.herokuapp.com)
  - [Video](https://www.youtube.com/watch?v=7d2qFLeYvRc)


  To try out this mobile app
    - [Expo](https://expo.io/@npatta01/food-app)
    - [Android](https://play.google.com/store/apps/details?id=com.rsnp.foodclassifier)
    - [iOS](https://itunes.apple.com/us/app/food-classifier/id1445356461?ls=1&mt=8)



code: https://github.com/npatta01/web-deep-learning-classifier

sampleImages:
  - name: Russian Blue
    url: https://upload.wikimedia.org/wikipedia/commons/d/de/Russian_Blue_kitten.jpg
  - name: British Shortair
    url: https://upload.wikimedia.org/wikipedia/commons/3/3b/British_shorthair_with_calico_coat_%282%29.jpg
  - name: English Cocker Spaniel
    url: https://upload.wikimedia.org/wikipedia/commons/8/86/English_Cocker_Spaniel_black_portrait.jpg
  - name: Jin Do (not in training data)
    url: https://upload.wikimedia.org/wikipedia/commons/d/db/%EC%A7%84%EB%8F%84%EC%9A%B8%ED%94%84%EB%8F%85_F1_%EC%9A%A9%EC%9D%B4_%EB%B6%80_%EB%AA%BD%EA%B3%A8%EB%8A%91%EB%8C%80%2C_%EB%AA%A8%EA%B2%AC_%EC%A7%84%EB%8F%84%EA%B0%9C.jpg
  - name: table (not in training & not a food)
    url: https://image.shutterstock.com/image-photo/brown-light-wooden-round-dining-260nw-588358070.jpg 
